version: "3.9"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d products"]
      interval: 3s
      timeout: 3s
      retries: 20

  product_service:
    build:
      context: ./backend/product_service
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: products
      # RabbitMQ not required for the "/" endpoint; app will warn but continue.
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
