services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d products"]
      interval: 3s
      timeout: 3s
      retries: 20
    ports:
      - "5432:5432"

  product_service:
    build:
      context: ./backend/product_service
    command: sh -c "sleep 5 && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: products
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
